openapi: 3.0.3
info:
  title: APS Bridge API
  description: Local HTTP bridge for APS operations from .NET Framework add-in
  version: 1.0.0

servers:
  - url: http://localhost:5000
    description: Local development

paths:
  /health:
    get:
      summary: Health check
      description: Verify the bridge is running
      operationId: healthCheck
      responses:
        '200':
          description: Bridge is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: healthy
                  version:
                    type: string
                    example: 1.0.0

  /auth/login:
    post:
      summary: Initiate OAuth login
      description: Start the OAuth flow - opens browser for user authentication
      operationId: login
      responses:
        '200':
          description: Login initiated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '409':
          description: Already in progress
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /auth/callback:
    post:
      summary: OAuth callback (internal)
      description: Processes OAuth callback - called by bridge's HTTP listener
      operationId: authCallback
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
                state:
                  type: string
      responses:
        '200':
          description: Callback processed
        '400':
          description: Invalid callback

  /auth/status:
    get:
      summary: Get authentication status
      description: Check if user is authenticated with APS
      operationId: getAuthStatus
      responses:
        '200':
          description: Current auth status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthStatusResponse'

  /auth/token/refresh:
    post:
      summary: Refresh access token
      description: Manually trigger token refresh
      operationId: refreshToken
      responses:
        '200':
          description: Token refreshed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        '401':
          description: Refresh failed - re-authentication required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /auth/logout:
    post:
      summary: Logout and clear tokens
      description: Clear stored tokens from Windows Credential Manager
      operationId: logout
      responses:
        '200':
          description: Logged out successfully

  /parameters:
    get:
      summary: Get COBie parameters
      description: Retrieve COBie parameter definitions from APS
      operationId: getParameters
      parameters:
        - name: accountId
          in: query
          required: true
          schema:
            type: string
        - name: collectionId
          in: query
          description: Filter by collection ID (optional, uses default COBie collection if not specified)
          schema:
            type: string
        - name: forceRefresh
          in: query
          description: Bypass cache and fetch from APS
          schema:
            type: boolean
          default: false
      responses:
        '200':
          description: Parameters retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  parameters:
                    type: array
                    items:
                      $ref: '#/components/schemas/ParameterDefinition'
                  cached:
                    type: boolean
                    description: True if returned from cache
                  cachedAt:
                    type: string
                    format: date-time
                    description: When cache was created (null if not cached)
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '503':
          description: APS service unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /parameters/specs:
    get:
      summary: Get available data types
      description: Retrieve all available parameter data types from APS
      operationId: getSpecs
      responses:
        '200':
          description: Specs retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  specs:
                    type: array
                    items:
                      $ref: '#/components/schemas/DataTypeSpec'

  /parameters/categories:
    get:
      summary: Get Revit categories
      description: Retrieve available Revit categories from APS
      operationId: getCategories
      parameters:
        - name: discipline
          in: query
          description: Filter by discipline (optional)
          schema:
            type: string
            enum: [architectural, structural, mep]
      responses:
        '200':
          description: Categories retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  categories:
                    type: array
                    items:
                      $ref: '#/components/schemas/CategoryInfo'

  /parameters/search:
    post:
      summary: Search parameters
      description: Search parameters with filters
      operationId: searchParameters
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchRequest'
      responses:
        '200':
          description: Search results
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/ParameterDefinition'

components:
  schemas:
    LoginResponse:
      type: object
      properties:
        loginUrl:
          type: string
          description: The URL the user should open in browser (if auto-open failed)
        message:
          type: string
          example: Login initiated - browser should open automatically

    AuthStatusResponse:
      type: object
      properties:
        isAuthenticated:
          type: boolean
        accountId:
          type: string
          nullable: true
        userId:
          type: string
          nullable: true
        expiresAt:
          type: string
          format: date-time
          nullable: true

    TokenResponse:
      type: object
      properties:
        accessToken:
          type: string
        refreshToken:
          type: string
        expiresAt:
          type: string
          format: date-time

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        message:
          type: string
        code:
          type: string
          description: Application-specific error code

    ParameterDefinition:
      type: object
      properties:
        id:
          type: string
          description: Unique parameter identifier
          example: a25628e6737f5e49b9754b648e4467d9
        name:
          type: string
          example: COBieTypeName
        description:
          type: string
          nullable: true
        dataTypeId:
          type: string
          description: APS data type identifier
          example: autodesk.revit.spec:text-1.0.0
        dataType:
          type: string
          enum: [Text, Integer, Number, Length, Area, Volume, Angle, FamilyType, YesNo, MultiValue, Unknown]
        instanceTypeAssociation:
          type: string
          enum: [INSTANCE, TYPE]
        categoryBindingIds:
          type: array
          items:
            type: string
          description: APS category identifiers
        labels:
          type: array
          items:
            type: string
        isHidden:
          type: boolean
        isArchived:
          type: boolean
        groupBindingId:
          type: string
          nullable: true

    DataTypeSpec:
      type: object
      properties:
        id:
          type: string
          example: autodesk.revit.spec:text-1.0.0
        name:
          type: string
          example: Text
        unitType:
          type: string
          nullable: true

    CategoryInfo:
      type: object
      properties:
        id:
          type: string
          example: autodesk.revit.category.instances:walls-1.0.0
        name:
          type: string
          example: Walls
        discipline:
          type: string
          enum: [architectural, structural, mep]
        level:
          type: string
          enum: [instances, types]

    SearchRequest:
      type: object
      properties:
        accountId:
          type: string
        collectionId:
          type: string
        searchedText:
          type: string
        dataTypeIds:
          type: array
          items:
            type: string
        isArchived:
          type: boolean
        sort:
          type: string
          enum: [NAME_ASCENDING, NAME_DESCENDING]
          default: NAME_ASCENDING
